# Generated by Django 4.0.5 on 2022-06-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpanel',
            old_name='adminid',
            new_name='t_id',
        ),
    ]
