# Generated by Django 4.0.5 on 2022-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_adminid_adminpanel_t_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpanel',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admin_panel'},
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='t_id',
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='admin_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='telegram id'),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Admin ismi'),
        ),
    ]
